version: '3'
services:

  #PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: aventurapp
    container_name: aventurapp-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
       - ./:/var/www
       - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - aventurapps-network

  #Nginx
  webserver:
    image: nginx:alpine
    container_name: aventurapp-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - aventurapps-network


  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: aventurapp-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: aventurapps
      MYSQL_ROOT_PASSWORD: toor
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - aventurapps-network


#Redes
networks:
  aventurapps-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
